# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: jackie198512@126.com
author_name: Jackie19
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab-store
project_short_description: A JupyterLab extension.
python_name: jupyterlab_store
repository: ''
test: false

